//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Area()
        {
            this.Units = new HashSet<Unit>();
            this.Communities = new HashSet<Community>();
            this.AssetsContractors = new HashSet<AssetsContractor>();
            this.Bookings = new HashSet<Booking>();
            this.Customers = new HashSet<Customer>();
            this.Locations = new HashSet<Location>();
            this.Properties = new HashSet<Property>();
            this.Staffs = new HashSet<Staff>();
            this.UnitBookings = new HashSet<UnitBooking>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string NameAR { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual City City2 { get; set; }
        public virtual City City3 { get; set; }
        public virtual City City4 { get; set; }
        public virtual City City5 { get; set; }
        public virtual City City6 { get; set; }
        public virtual City City7 { get; set; }
        public virtual City City8 { get; set; }
        public virtual City City9 { get; set; }
        public virtual City City10 { get; set; }
        public virtual City City11 { get; set; }
        public virtual City City12 { get; set; }
        public virtual City City13 { get; set; }
        public virtual City City14 { get; set; }
        public virtual City City15 { get; set; }
        public virtual City City16 { get; set; }
        public virtual City City17 { get; set; }
        public virtual City City18 { get; set; }
        public virtual City City19 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Country Country2 { get; set; }
        public virtual Country Country3 { get; set; }
        public virtual Country Country4 { get; set; }
        public virtual Country Country5 { get; set; }
        public virtual Country Country6 { get; set; }
        public virtual Country Country7 { get; set; }
        public virtual Country Country8 { get; set; }
        public virtual Country Country9 { get; set; }
        public virtual Country Country10 { get; set; }
        public virtual Country Country11 { get; set; }
        public virtual Country Country12 { get; set; }
        public virtual Country Country13 { get; set; }
        public virtual Country Country14 { get; set; }
        public virtual Country Country15 { get; set; }
        public virtual Country Country16 { get; set; }
        public virtual Country Country17 { get; set; }
        public virtual Country Country18 { get; set; }
        public virtual Country Country19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit> Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Community> Communities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetsContractor> AssetsContractors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitBooking> UnitBookings { get; set; }
    }
}
