//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.AssetImages = new HashSet<AssetImage>();
            this.AssetsSpecifications = new HashSet<AssetsSpecification>();
        }
    
        public long ID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<long> AssetsContractorID { get; set; }
        public Nullable<long> AssetsParentCategoryID { get; set; }
        public Nullable<long> AssetsCategoryID { get; set; }
        public Nullable<long> AssetsProductID { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public Nullable<long> StaffID { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> WarrantyExpiryDate { get; set; }
        public string PurchaseType { get; set; }
        public string DepreciationType { get; set; }
        public Nullable<decimal> UsefulLife { get; set; }
        public Nullable<decimal> ResidualValue { get; set; }
        public Nullable<decimal> RatePercentage { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetImage> AssetImages { get; set; }
        public virtual AssetsContractor AssetsContractor { get; set; }
        public virtual AssetsCategory AssetsCategory { get; set; }
        public virtual AssetsCategory AssetsCategory1 { get; set; }
        public virtual AssetsProduct AssetsProduct { get; set; }
        public virtual Department Department { get; set; }
        public virtual Location Location { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetsSpecification> AssetsSpecifications { get; set; }
    }
}
