//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsContractor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetsContractor()
        {
            this.Assets = new HashSet<Asset>();
        }
    
        public long ID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> AreaID { get; set; }
        public string CountryTxt { get; set; }
        public string CityTxt { get; set; }
        public string IDNo { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public string ContractorCode { get; set; }
        public string PhoneCode { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Designation { get; set; }
        public string CPName { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string ZipCode { get; set; }
        public string About { get; set; }
        public string Logo { get; set; }
        public string CoverImage { get; set; }
        public string TRN { get; set; }
        public string Website { get; set; }
        public string License { get; set; }
        public string FAX { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
    }
}
