//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingCancellations = new HashSet<BookingCancellation>();
            this.BookingImages = new HashSet<BookingImage>();
            this.BookingReviews = new HashSet<BookingReview>();
        }
    
        public long ID { get; set; }
        public string BookingNo { get; set; }
        public Nullable<long> VendorID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> ServiceID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> AreaID { get; set; }
        public string SessionID { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerCity { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneCode { get; set; }
        public string Contact { get; set; }
        public string PhoneCode2 { get; set; }
        public string Contact2 { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string PoBox { get; set; }
        public string ZipCode { get; set; }
        public string EmiratesID { get; set; }
        public Nullable<System.DateTime> EmiratesIDExpiry { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportExpiry { get; set; }
        public Nullable<System.DateTime> DateOfVisit { get; set; }
        public Nullable<System.TimeSpan> TimeOfVisit { get; set; }
        public string CustomNote { get; set; }
        public string MapLocation { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public string Status { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsEarningCaptured { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public string CouponCode { get; set; }
        public Nullable<decimal> CouponDiscount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> RedeemAmount { get; set; }
        public Nullable<decimal> VisitCharges { get; set; }
        public Nullable<decimal> DeliveryCharges { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingCancellation> BookingCancellations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingImage> BookingImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingReview> BookingReviews { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Service Service { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
