//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessSetting()
        {
            this.BusinessBranchSettings = new HashSet<BusinessBranchSetting>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public string TitleAr { get; set; }
        public string Whatsapp { get; set; }
        public string FIrstMessage { get; set; }
        public string FIrstMessageAr { get; set; }
        public string MapIframe { get; set; }
        public string StreetAddress { get; set; }
        public string StreetAddressAr { get; set; }
        public string PhoneCode { get; set; }
        public string Contact { get; set; }
        public string PhoneCode2 { get; set; }
        public string Contact2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string WorkingDays { get; set; }
        public string WorkingTime { get; set; }
        public string AndroidAppUrl { get; set; }
        public string IosAppUrl { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Youtube { get; set; }
        public string Twitter { get; set; }
        public string Snapchat { get; set; }
        public string LinkedIn { get; set; }
        public string Behnace { get; set; }
        public string Pinterest { get; set; }
        public string FCMKey { get; set; }
        public string GoogleMapKey { get; set; }
        public string CustomerFCMKey { get; set; }
        public string WorkForceFCMKey { get; set; }
        public string PartnerFCMKey { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public string NameAr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessBranchSetting> BusinessBranchSettings { get; set; }
    }
}
