//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessBranchSetting
    {
        public long ID { get; set; }
        public Nullable<long> BusinessSettingID { get; set; }
        public string Name { get; set; }
        public string NameAr { get; set; }
        public string MapIframe { get; set; }
        public string StreetAddress { get; set; }
        public string StreetAddressAr { get; set; }
        public string Contact { get; set; }
        public string Contact2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WorkingDays { get; set; }
        public string WorkingTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Image { get; set; }
    
        public virtual BusinessSetting BusinessSetting { get; set; }
    }
}
