//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityFeature
    {
        public long ID { get; set; }
        public Nullable<long> CommunityID { get; set; }
        public Nullable<long> FeatureID { get; set; }
        public string Description { get; set; }
        public string DescriptionAr { get; set; }
        public string Cover { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual Community Community { get; set; }
        public virtual Community Community1 { get; set; }
        public virtual Community Community2 { get; set; }
        public virtual Community Community3 { get; set; }
        public virtual Community Community4 { get; set; }
        public virtual Community Community5 { get; set; }
        public virtual Community Community6 { get; set; }
        public virtual Community Community7 { get; set; }
        public virtual Community Community8 { get; set; }
        public virtual Community Community9 { get; set; }
        public virtual Community Community10 { get; set; }
        public virtual Community Community11 { get; set; }
        public virtual Community Community12 { get; set; }
        public virtual Community Community13 { get; set; }
        public virtual Community Community14 { get; set; }
        public virtual Community Community15 { get; set; }
        public virtual Community Community16 { get; set; }
        public virtual Community Community17 { get; set; }
        public virtual Community Community18 { get; set; }
        public virtual Community Community19 { get; set; }
        public virtual Feature Feature { get; set; }
    }
}
