//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Appointments = new HashSet<Appointment>();
            this.BookingCancellations = new HashSet<BookingCancellation>();
            this.Bookings = new HashSet<Booking>();
            this.CouponRedemptions = new HashSet<CouponRedemption>();
            this.CustomerCoupons = new HashSet<CustomerCoupon>();
            this.CustomerDocuments = new HashSet<CustomerDocument>();
            this.CustomerDocumentDetails = new HashSet<CustomerDocumentDetail>();
            this.CustomerSuggestions = new HashSet<CustomerSuggestion>();
            this.ServiceBookings = new HashSet<ServiceBooking>();
            this.ServicebookingImages = new HashSet<ServicebookingImage>();
            this.ServiceRatings = new HashSet<ServiceRating>();
            this.BookingReviews = new HashSet<BookingReview>();
            this.CustomerSessions = new HashSet<CustomerSession>();
            this.Enquiries = new HashSet<Enquiry>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Quotations = new HashSet<Quotation>();
            this.UnitBookings = new HashSet<UnitBooking>();
            this.UnitEnquiries = new HashSet<UnitEnquiry>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> AreaID { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerCity { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Logo { get; set; }
        public string PhoneCode { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string PoBox { get; set; }
        public string ZipCode { get; set; }
        public string EmiratesID { get; set; }
        public Nullable<System.DateTime> EmiratesIDExpiry { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportExpiry { get; set; }
        public Nullable<int> Salt { get; set; }
        public string Password { get; set; }
        public Nullable<int> OTP { get; set; }
        public string AuthorizationCode { get; set; }
        public Nullable<System.DateTime> AuthorizationExpiry { get; set; }
        public string AccountType { get; set; }
        public Nullable<long> ReferredBy { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<bool> IsBookingNoticationAllowed { get; set; }
        public Nullable<bool> IsPushNotificationAllowed { get; set; }
        public Nullable<bool> IsGuest { get; set; }
        public Nullable<bool> IsContactVerified { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<bool> IsContactOTPAccess { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingCancellation> BookingCancellations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponRedemption> CouponRedemptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCoupon> CustomerCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDocument> CustomerDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDocumentDetail> CustomerDocumentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSuggestion> CustomerSuggestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceBooking> ServiceBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicebookingImage> ServicebookingImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRating> ServiceRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingReview> BookingReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSession> CustomerSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enquiry> Enquiries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitBooking> UnitBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitEnquiry> UnitEnquiries { get; set; }
    }
}
