//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDocument
    {
        public long ID { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<long> CustomerDocumentTypeID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string Path { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public string Relation { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> IsFamily { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CustomerRelationID { get; set; }
    
        public virtual CustomerRelation CustomerRelation { get; set; }
        public virtual CustomerDocumentType CustomerDocumentType { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
