//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSetting
    {
        public long ID { get; set; }
        public string EmailAddress { get; set; }
        public string ContactEmail { get; set; }
        public string Password { get; set; }
        public string Port { get; set; }
        public string Host { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> EnableSSL { get; set; }
    }
}
