//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCandidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobCandidate()
        {
            this.CandidateEducations = new HashSet<CandidateEducation>();
            this.CandidateExperiences = new HashSet<CandidateExperience>();
        }
    
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Nationality { get; set; }
        public string VISAStatus { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string TotalExperience { get; set; }
        public string UAEExperience { get; set; }
        public string INTExperience { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string NoticePeriod { get; set; }
        public string DrivingLicense { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Cv { get; set; }
        public string MaritalStatus { get; set; }
        public string Photo { get; set; }
        public Nullable<long> JobID { get; set; }
        public string UCC { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsFlaged { get; set; }
        public Nullable<bool> MarkAsRead { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> Schedule { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateEducation> CandidateEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateExperience> CandidateExperiences { get; set; }
        public virtual JobOpening JobOpening { get; set; }
    }
}
