//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOpening
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobOpening()
        {
            this.JobCandidates = new HashSet<JobCandidate>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string Title { get; set; }
        public string TitleAr { get; set; }
        public string Requirements { get; set; }
        public string RequirementsAr { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string Location { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCandidate> JobCandidates { get; set; }
    }
}
