//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductAttribute()
        {
            this.ProductVariants = new HashSet<ProductVariant>();
            this.ProductVariationAttributes = new HashSet<ProductVariationAttribute>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> AttributeID { get; set; }
        public string Value { get; set; }
        public string ValueAr { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariant> ProductVariants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariationAttribute> ProductVariationAttributes { get; set; }
    }
}
