//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductVariation()
        {
            this.ProductVariationAttributes = new HashSet<ProductVariationAttribute>();
            this.ProductVariationImages = new HashSet<ProductVariationImage>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> RegularPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<System.DateTime> SalePriceFrom { get; set; }
        public Nullable<System.DateTime> SalePriceTo { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Threshold { get; set; }
        public string StockStatus { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public string Description { get; set; }
        public string DescriptionAr { get; set; }
        public Nullable<bool> IsManageStock { get; set; }
        public Nullable<bool> SoldIndividually { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariationAttribute> ProductVariationAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariationImage> ProductVariationImages { get; set; }
    }
}
