//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductRating()
        {
            this.ProductRatingImages = new HashSet<ProductRatingImage>();
        }
    
        public long ID { get; set; }
        public Nullable<long> OrderDetailID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<double> Rating { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRatingImage> ProductRatingImages { get; set; }
    }
}
