//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        public long ID { get; set; }
        public string SKU { get; set; }
        public string Name { get; set; }
        public string NameAr { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<bool> IsManageStock { get; set; }
        public string StockStatus { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> ProductAttributeID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductAttribute ProductAttribute { get; set; }
    }
}
