//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductAttributes = new HashSet<ProductAttribute>();
            this.ProductAttributeSettings = new HashSet<ProductAttributeSetting>();
            this.ProductCategories = new HashSet<ProductCategory>();
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductRatings = new HashSet<ProductRating>();
            this.ProductTags = new HashSet<ProductTag>();
            this.ProductVariants = new HashSet<ProductVariant>();
            this.ProductVariationAttributes = new HashSet<ProductVariationAttribute>();
            this.ProductVariationImages = new HashSet<ProductVariationImage>();
            this.ProductVariations = new HashSet<ProductVariation>();
            this.QuotationDetails = new HashSet<QuotationDetail>();
        }
    
        public long ID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public Nullable<long> BrandID { get; set; }
        public Nullable<long> ShippingClassID { get; set; }
        public string SKU { get; set; }
        public string Slug { get; set; }
        public string Name { get; set; }
        public string NameAr { get; set; }
        public string ShortDescription { get; set; }
        public string ShortDescriptionAr { get; set; }
        public string LongDescription { get; set; }
        public string LongDescriptionAr { get; set; }
        public string MobileDescription { get; set; }
        public string MobileDescriptionAr { get; set; }
        public Nullable<decimal> RegularPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<System.DateTime> SalePriceFrom { get; set; }
        public Nullable<System.DateTime> SalePriceTo { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Threshold { get; set; }
        public string Thumbnail { get; set; }
        public string Type { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public string PurchaseNote { get; set; }
        public Nullable<bool> EnableReviews { get; set; }
        public Nullable<bool> IsSoldIndividually { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<bool> AllowMultiplePerOrder { get; set; }
        public Nullable<int> StockStatus { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<bool> IsRecommended { get; set; }
        public Nullable<bool> IsManageStock { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTaxInclusive { get; set; }
        public Nullable<System.DateTime> PublishStartDate { get; set; }
        public Nullable<System.DateTime> PublishEndDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAttribute> ProductAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAttributeSetting> ProductAttributeSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRating> ProductRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTag> ProductTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariant> ProductVariants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariationAttribute> ProductVariationAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariationImage> ProductVariationImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariation> ProductVariations { get; set; }
        public virtual ShippingClass ShippingClass { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationDetail> QuotationDetails { get; set; }
    }
}
