//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectImages = new HashSet<ProjectImage>();
            this.ProjectTags = new HashSet<ProjectTag>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ProjectTypeID { get; set; }
        public string Name { get; set; }
        public string NameAr { get; set; }
        public string Slug { get; set; }
        public string Thumbnail { get; set; }
        public string LocationImage { get; set; }
        public string ShortDescription { get; set; }
        public string ShortDescriptionAr { get; set; }
        public string Description { get; set; }
        public string DescriptionAr { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Locality { get; set; }
        public string Video { get; set; }
        public string Developer { get; set; }
        public string Broucher { get; set; }
        public string Faqs { get; set; }
        public string FaqsAr { get; set; }
        public Nullable<decimal> PriceStart { get; set; }
        public Nullable<decimal> PriceEnd { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> Bedrooms { get; set; }
        public Nullable<int> Baths { get; set; }
        public Nullable<decimal> AreaStart { get; set; }
        public Nullable<decimal> AreaEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectImage> ProjectImages { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTag> ProjectTags { get; set; }
    }
}
