//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectImage
    {
        public long ID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public string Image { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
