//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyFeature
    {
        public long ID { get; set; }
        public Nullable<long> PropertyID { get; set; }
        public Nullable<long> FeatureID { get; set; }
        public string Description { get; set; }
        public string DescriptionAr { get; set; }
        public string Cover { get; set; }
        public Nullable<int> Position { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual Property Property { get; set; }
    }
}
