//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quotation()
        {
            this.QuotationDetails = new HashSet<QuotationDetail>();
            this.QuotationNotes = new HashSet<QuotationNote>();
        }
    
        public long ID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public Nullable<long> StaffID { get; set; }
        public Nullable<long> BookingID { get; set; }
        public Nullable<long> ServiceCategoryID { get; set; }
        public Nullable<long> ServiceID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ServiceBooking ServiceBooking { get; set; }
        public virtual Service Service { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationDetail> QuotationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationNote> QuotationNotes { get; set; }
    }
}
