//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceBooking()
        {
            this.CouponRedemptions = new HashSet<CouponRedemption>();
            this.Quotations = new HashSet<Quotation>();
            this.ServicebookingImages = new HashSet<ServicebookingImage>();
            this.ServiceRatings = new HashSet<ServiceRating>();
        }
    
        public long ID { get; set; }
        public string BookingNo { get; set; }
        public Nullable<long> ServiceCategoryID { get; set; }
        public Nullable<long> ServiceID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerContact { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<System.DateTime> DateOfVisit { get; set; }
        public Nullable<System.TimeSpan> TimeOfVisit { get; set; }
        public string Description { get; set; }
        public Nullable<long> StaffID { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> VisitCharges { get; set; }
        public Nullable<decimal> DeliveryCharges { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public string CouponCode { get; set; }
        public Nullable<decimal> CouponDiscount { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> IsPayed { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public string PaymentRef { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string PaymentStatus { get; set; }
        public string CancellationReason { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> AreaID { get; set; }
        public string SessionID { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerCity { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneCode { get; set; }
        public string PoBox { get; set; }
        public string ZipCode { get; set; }
        public string EmiratesID { get; set; }
        public Nullable<System.DateTime> EmiratesIDExpiry { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportExpiry { get; set; }
        public string MapLocation { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<bool> IsEarningCaptured { get; set; }
        public Nullable<decimal> RedeemAmount { get; set; }
        public Nullable<bool> IsQuoteApproved { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponRedemption> CouponRedemptions { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicebookingImage> ServicebookingImages { get; set; }
        public virtual Service Service { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRating> ServiceRatings { get; set; }
    }
}
