//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Assets = new HashSet<Asset>();
            this.Quotations = new HashSet<Quotation>();
            this.ServiceBookings = new HashSet<ServiceBooking>();
            this.StaffSessions = new HashSet<StaffSession>();
            this.StaffSuggestions = new HashSet<StaffSuggestion>();
        }
    
        public long ID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public Nullable<long> StaffRoleID { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> AreaID { get; set; }
        public string CountryTxt { get; set; }
        public string CityTxt { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public string EmiratesID { get; set; }
        public Nullable<System.DateTime> EmiratesIDExpiry { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportExpiry { get; set; }
        public string Password { get; set; }
        public Nullable<int> Salt { get; set; }
        public Nullable<int> OTP { get; set; }
        public Nullable<bool> IsPushNotificationAllowed { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<bool> IsContactOTPAccess { get; set; }
        public Nullable<bool> IsContactVerified { get; set; }
        public string AuthorizationCode { get; set; }
        public Nullable<bool> IsAuthorized { get; set; }
        public Nullable<System.DateTime> AuthorizationExpiry { get; set; }
        public string StaffCode { get; set; }
        public string PhoneCode { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string ZipCode { get; set; }
        public string About { get; set; }
        public string Logo { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Department Department { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceBooking> ServiceBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffSession> StaffSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffSuggestion> StaffSuggestions { get; set; }
        public virtual StaffRole StaffRole { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
