//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxSetting
    {
        public long ID { get; set; }
        public string TaxName { get; set; }
        public string TaxNameAr { get; set; }
        public string TaxDescription { get; set; }
        public string TaxDescriptionAr { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
