//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string NameAr { get; set; }
        public string About { get; set; }
        public string AboutAr { get; set; }
        public string Designation { get; set; }
        public string DesignationAr { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
