//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketMessage
    {
        public long ID { get; set; }
        public Nullable<long> TicketID { get; set; }
        public Nullable<long> TicketDocumentID { get; set; }
        public Nullable<long> SenderID { get; set; }
        public string SenderType { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
