//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long ID { get; set; }
        public string InvoiceCode { get; set; }
        public string NameOnCard { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string MaskCardNo { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string SessionID { get; set; }
        public Nullable<long> RecordID { get; set; }
        public string RawResponse { get; set; }
        public string TransactionType { get; set; }
        public string TransactionID { get; set; }
        public string PaymentRef { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
