//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitAmenity
    {
        public long ID { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<long> AmenityID { get; set; }
        public Nullable<float> Size { get; set; }
    
        public virtual Amenity Amenity { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
