//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unit()
        {
            this.UnitAmenities = new HashSet<UnitAmenity>();
            this.UnitBookings = new HashSet<UnitBooking>();
            this.UnitEnquiries = new HashSet<UnitEnquiry>();
            this.UnitImages = new HashSet<UnitImage>();
            this.UnitPaymentPlans = new HashSet<UnitPaymentPlan>();
        }
    
        public long ID { get; set; }
        public Nullable<long> PropertyID { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> AreaID { get; set; }
        public long UnitTypeID { get; set; }
        public string Title { get; set; }
        public string TitleAr { get; set; }
        public string Slug { get; set; }
        public string Thumbnail { get; set; }
        public string Description { get; set; }
        public string DescriptionAr { get; set; }
        public Nullable<double> Size { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<decimal> LandRegistrationFee { get; set; }
        public Nullable<decimal> OqoodAmount { get; set; }
        public Nullable<decimal> DubaiLandDepartmentFee { get; set; }
        public string PropertyUsage { get; set; }
        public string FloorPlan { get; set; }
        public string Broucher { get; set; }
        public string Address { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> NoOfBedrooms { get; set; }
        public Nullable<int> NoOfGarages { get; set; }
        public Nullable<int> NoOfRooms { get; set; }
        public Nullable<int> NoOfBaths { get; set; }
        public Nullable<int> NoOfDinings { get; set; }
        public Nullable<int> NoOfLaundry { get; set; }
        public Nullable<int> BuildYear { get; set; }
        public string Video { get; set; }
        public string VRTour { get; set; }
        public bool IsPublished { get; set; }
        public bool IsFeatured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public string ZipCode { get; set; }
        public string UnitNo { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public Nullable<int> GarageSize { get; set; }
        public Nullable<decimal> BookingAmount { get; set; }
        public string LocationDescription { get; set; }
        public string LocationDescriptionAr { get; set; }
        public Nullable<int> EMI { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Property Property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitAmenity> UnitAmenities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitBooking> UnitBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitEnquiry> UnitEnquiries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitImage> UnitImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitPaymentPlan> UnitPaymentPlans { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
