//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitBooking
    {
        public long ID { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerCity { get; set; }
        public string BookingNo { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<long> AreaID { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string PoBox { get; set; }
        public string ZipCode { get; set; }
        public string EmiratesID { get; set; }
        public Nullable<System.DateTime> EmiratesIDExpiry { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportExpiry { get; set; }
        public string BookingStatus { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> Status { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string SessionID { get; set; }
        public Nullable<bool> IsEarningCaptured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual UnitBookingsPaymentHistory UnitBookingsPaymentHistory { get; set; }
    }
}
