//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitPaymentPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnitPaymentPlan()
        {
            this.UnitBookingsPaymentHistories = new HashSet<UnitBookingsPaymentHistory>();
        }
    
        public long ID { get; set; }
        public Nullable<long> UnitID { get; set; }
        public string Milestones { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitBookingsPaymentHistory> UnitBookingsPaymentHistories { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
