//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRolePrivilege
    {
        public long ID { get; set; }
        public Nullable<long> UserRoleID { get; set; }
        public Nullable<long> RouteID { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual Route Route1 { get; set; }
        public virtual Route Route2 { get; set; }
        public virtual Route Route3 { get; set; }
        public virtual Route Route4 { get; set; }
        public virtual Route Route5 { get; set; }
        public virtual Route Route6 { get; set; }
        public virtual Route Route7 { get; set; }
        public virtual Route Route8 { get; set; }
        public virtual Route Route9 { get; set; }
        public virtual Route Route10 { get; set; }
        public virtual Route Route11 { get; set; }
        public virtual Route Route12 { get; set; }
        public virtual Route Route13 { get; set; }
        public virtual Route Route14 { get; set; }
        public virtual Route Route15 { get; set; }
        public virtual Route Route16 { get; set; }
        public virtual Route Route17 { get; set; }
        public virtual Route Route18 { get; set; }
        public virtual Route Route19 { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual UserRole UserRole1 { get; set; }
        public virtual UserRole UserRole2 { get; set; }
        public virtual UserRole UserRole3 { get; set; }
        public virtual UserRole UserRole4 { get; set; }
        public virtual UserRole UserRole5 { get; set; }
        public virtual UserRole UserRole6 { get; set; }
        public virtual UserRole UserRole7 { get; set; }
        public virtual UserRole UserRole8 { get; set; }
        public virtual UserRole UserRole9 { get; set; }
        public virtual UserRole UserRole10 { get; set; }
        public virtual UserRole UserRole11 { get; set; }
        public virtual UserRole UserRole12 { get; set; }
        public virtual UserRole UserRole13 { get; set; }
        public virtual UserRole UserRole14 { get; set; }
        public virtual UserRole UserRole15 { get; set; }
        public virtual UserRole UserRole16 { get; set; }
        public virtual UserRole UserRole17 { get; set; }
        public virtual UserRole UserRole18 { get; set; }
        public virtual UserRole UserRole19 { get; set; }
    }
}
