//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorUserRolePrivilege
    {
        public long ID { get; set; }
        public Nullable<long> UserRoleID { get; set; }
        public Nullable<long> RouteID { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual VendorUserRole VendorUserRole { get; set; }
    }
}
