//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.Assets = new HashSet<Asset>();
            this.AssetsCategories = new HashSet<AssetsCategory>();
            this.AssetsContractors = new HashSet<AssetsContractor>();
            this.AssetsProducts = new HashSet<AssetsProduct>();
            this.Bookings = new HashSet<Booking>();
            this.Departments = new HashSet<Department>();
            this.Locations = new HashSet<Location>();
            this.Products = new HashSet<Product>();
            this.Quotations = new HashSet<Quotation>();
            this.QuotationDetails = new HashSet<QuotationDetail>();
            this.ServiceBookings = new HashSet<ServiceBooking>();
            this.Services = new HashSet<Service>();
            this.Staffs = new HashSet<Staff>();
            this.StaffRoles = new HashSet<StaffRole>();
            this.StaffSuggestions = new HashSet<StaffSuggestion>();
            this.Tickets = new HashSet<Ticket>();
            this.VendorDocuments = new HashSet<VendorDocument>();
            this.VendorSuggestions = new HashSet<VendorSuggestion>();
            this.VendorWalletShareHistories = new HashSet<VendorWalletShareHistory>();
            this.VendorWalletShares = new HashSet<VendorWalletShare>();
            this.VendorWithdrawalRequests = new HashSet<VendorWithdrawalRequest>();
            this.VendorServices = new HashSet<VendorService>();
            this.VendorTransactionHistories = new HashSet<VendorTransactionHistory>();
            this.VendorUsers = new HashSet<VendorUser>();
            this.VendorUserRoles = new HashSet<VendorUserRole>();
        }
    
        public long ID { get; set; }
        public string VendorCode { get; set; }
        public string Name { get; set; }
        public string NameAr { get; set; }
        public string Slug { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Salt { get; set; }
        public string Logo { get; set; }
        public string CoverImage { get; set; }
        public string Contact { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string IDNo { get; set; }
        public string TRN { get; set; }
        public string Website { get; set; }
        public string License { get; set; }
        public string FAX { get; set; }
        public string About { get; set; }
        public string AboutAr { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerCity { get; set; }
        public Nullable<long> VendorPackageID { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public string BaseCurrency { get; set; }
        public Nullable<int> OTP { get; set; }
        public string BankName { get; set; }
        public string AccountHolderName { get; set; }
        public string BankAccountNumber { get; set; }
        public string IBAN { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string RefreshToken { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> AuthorizationExpiry { get; set; }
        public Nullable<bool> IsExpiry { get; set; }
        public Nullable<bool> IsContactVerified { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsAuthorized { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> VendorTypeID { get; set; }
        public Nullable<long> VendorSectionID { get; set; }
        public Nullable<long> VendorIndustryID { get; set; }
        public Nullable<long> BankID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetsCategory> AssetsCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetsContractor> AssetsContractors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetsProduct> AssetsProducts { get; set; }
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationDetail> QuotationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceBooking> ServiceBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffRole> StaffRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffSuggestion> StaffSuggestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorDocument> VendorDocuments { get; set; }
        public virtual VendorIndustry VendorIndustry { get; set; }
        public virtual VendorPackage VendorPackage { get; set; }
        public virtual VendorSection VendorSection { get; set; }
        public virtual VendorType VendorType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorSuggestion> VendorSuggestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorWalletShareHistory> VendorWalletShareHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorWalletShare> VendorWalletShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorWithdrawalRequest> VendorWithdrawalRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorService> VendorServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorTransactionHistory> VendorTransactionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorUser> VendorUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorUserRole> VendorUserRoles { get; set; }
    }
}
