//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorSession
    {
        public long ID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public string AccessToken { get; set; }
        public string FirebaseToken { get; set; }
        public string DeviceID { get; set; }
        public Nullable<bool> SessionState { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
