//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorTransactionHistory
    {
        public long ID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public Nullable<long> VendorPackageID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public string Status { get; set; }
    
        public virtual VendorPackage VendorPackage { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
