//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorUser
    {
        public long ID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> OTP { get; set; }
        public Nullable<bool> IsContactVerified { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
        public Nullable<long> UserRoleID { get; set; }
        public Nullable<long> Salt { get; set; }
        public string AuthorizationCode { get; set; }
        public Nullable<System.DateTime> AuthorizationExpiry { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual VendorUserRole VendorUserRole { get; set; }
    }
}
