//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorSuggestion
    {
        public long ID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public string Suggestion { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
